### PR TITLE
Fixes bone-setting surgery

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

Currently, the bone-fixing surgery does not function. It needs you to go incision > gel > setter > gel, but you can't apply the gel for the second time - and if you COULD, the limb would immediately rebreak.
This makes two changes:
- The procedure is now incision > setter > gel. 
- The surgeon will be prevented from applying the gel if the limb is above the minimum damage to break (and would instantly break upon being fixed).

## Why It's Good For The Game

Aside from allowing the surgery to be performed, this is good because - realistically speaking - if a limb is _so damaged_ that it'd break, it doesn't make much sense that you could fix the bone in the first place.

## Changelog
:cl:
tweak: bone-fixing surgery is now done by applying a bone setter and then bone gel
tweak: bones cannot be fixed if their limb has taken enough damage to break
/:cl:

### CODE REVIEW

**Comment by GeminusCity** [comment]
Before we add this PR, we'll need to port over a guide to surgery to the GC wiki, with the updated steps.

**Comment by faaaay** [comment]
Sure, I can get that done.

**Comment by faaaay** [comment]
Oh, I don't have the permissions needed to create wiki pages.

**Comment by faaaay** [comment]
Scratch that, I do and the wiki is updated.

**Pull request merged**
